server:
  port: 8520
  address:

spring:
  application:
    name: oes-exam
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /
  redis:
    database: 0
    host: redis
    port: 6379
    #    password:
    timeout: 2000
  cache:
    redis:
      cache-null-values: false
      time-to-live: 10m
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
    stream:
      bindings:
        score-input:
          destination: exam-score
          group: average
        score-output:
          destination: exam-score
        ding-output:
          destination: ding-log
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${spring.rabbitmq.host}
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                virtual-host: ${spring.rabbitmq.virtual-host}
  datasource:
    url: jdbc:mysql://mariadb:3306/oes?characterEncoding=utf8&autoReconnect=true&useSSL=false
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${spring.datasource.url}
      username: root
      password: housirvip
      max-active: 30
      min-idle: 5
      initial-size: 5
      max-wait: 20000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      use-global-data-source-stat: true
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  pageSizeZero: true
  rowBoundsWithCount: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  connect-timeout: 600
  read-timeout: 6000
  ok-to-retry-on-all-operations: true
  max-auto-retries-next-server: 2
  max-auto-retries: 1

jwt:
  secret: changeIt
  expire: 21600
  delay: 60

exam:
  score-async: true
  time-limit: 2