server:
  port: 8080
  address:

logging:
  level:
    root: warn

spring:
  application:
    name: oes-gateway
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        hostname: housirvipdeimac.lan
    #        health-check-interval: 5s
    gateway:
      routes:
        - id: auth
          uri: lb://oes-user
          predicates:
            - Path=/auth/**
        - id: user
          uri: lb://oes-user
          predicates:
            - Path=/user/**
        - id: token
          uri: lb://oes-user
          predicates:
            - Path=/token/**
        - id: user-admin
          uri: lb://oes-user
          predicates:
            - Path=/user-admin/**
        - id: paper
          uri: lb://oes-exam
          predicates:
            - Path=/paper/**
        - id: exam
          uri: lb://oes-exam
          predicates:
            - Path=/exam/**
        - id: exam-admin
          uri: lb://oes-exam
          predicates:
            - Path=/exam-admin/**
        - id: order
          uri: lb://oes-store
          predicates:
            - Path=/order/**
        - id: store
          uri: lb://oes-store
          predicates:
            - Path=/store/**
        - id: store-admin
          uri: lb://oes-store
          predicates:
            - Path=/store-admin/**
        - id: ticket
          uri: lb://oes-support
          predicates:
            - Path=/ticket/**
        - id: notice
          uri: lb://oes-support
          predicates:
            - Path=/notice/**
        - id: noauth
          uri: lb://oes-support
          predicates:
            - Path=/noauth/**
        - id: support-admin
          uri: lb://oes-support
          predicates:
            - Path=/support-admin/**