server:
  port: 8080
  address:

spring:
  application:
    name: oes-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        hostname: housirvipdeimac.lan
  #        health-check-interval: 5s
    gateway:
      routes:
      - id: auth
        uri: lb://oes-user
        predicates:
          - Path=/auth/**
      - id: user
        uri: lb://oes-user
        predicates:
          - Path=/user/**
      - id: user-admin
        uri: lb://oes-user
        predicates:
          - Path=/user-admin/**/**
      - id: paper
        uri: lb://oes-exam
        predicates:
          - Path=/paper/**
      - id: exam
        uri: lb://oes-exam
        predicates:
          - Path=/exam/**
      - id: exam-admin
        uri: lb://oes-exam
        predicates:
          - Path=/exam-admin/**/**

