server:
  port: 8080
  address:

spring:
  application:
    name: oes-gateway
  cloud:
    consul:
      host: ubuntu.lan
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        hostname: mibookpro.lan
  #        health-check-interval: 5s
    gateway:
      routes:
        - id: 163_route
          uri: http://www.163.com/
          predicates:
            - Path=/163