server:
  port: 8080
  address:

spring:
  application:
    name: oes-gateway
  cloud:
    consul:
      host: ubuntu.lan
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        hostname: mibookpro.lan
  #        health-check-interval: 5s
    gateway:
      routes:
      - id: test
        uri: http://www.163.com/
        predicates:
          - Path=/test,/asd
      - id: oes-exam
        uri: lb://oes-exam
        predicates:
          - Path=/papers