server:
  port: 8000

spring:
  application:
    name: oes-base
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8