server:
  port: 8000

spring:
  application:
    name: oes-feign
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: false
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  # 设置连接超时时间
  connect-timeout: 600
  # 设置读取超时时间
  read-timeout: 6000
  # 对所有操作请求都进行重试
  ok-to-retry-on-all-operations: true
  # 切换实例的重试次数
  max-auto-retries-next-server: 2
  # 对当前实例的重试次数
  max-auto-retries: 1
